# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: mixed-line-ending

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Use the latest stable version
    hooks:
      - id: isort
        name: isort (llm-utils src)
        files: ^src/
        args: ['--profile=black', '--line-length=120']
      - id: isort
        name: isort (llm-utils tests)
        files: ^tests/
        args: ['--profile=black', '--line-length=120']
      - id: isort
        name: isort (llm-utils root)
        files: ^test\.py$
        args: ['--profile=black', '--line-length=120']

  - repo: https://github.com/psf/black
    rev: 23.3.0  # Use the latest stable version
    hooks:
      - id: black
        name: black (llm-utils src)
        files: ^src/
        args: ['--line-length', '120']
      - id: black
        name: black (llm-utils tests)
        files: ^tests/
        args: ['--line-length', '120']
      - id: black
        name: black (llm-utils root)
        files: ^test\.py$
        args: ['--line-length', '120']
